---
abstract: 'Extract meta information from image files'
author:
  - 'Slaven Rezic <srezic@cpan.org>'
  - 'Gisle Aas <gisle@ActiveState.com'
  - Tels
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-Info
no_index:
  directory:
    - t
    - inc
    - dev
    - img
    - xt
recommends:
  Bundle::Image::Info::PNG: 0
  Bundle::Image::Info::SVG: 0
  Bundle::Image::Info::XBM: 0
  Bundle::Image::Info::XPM: 0
requires:
  perl: 5.006
resources:
  repository: git://github.com/eserte/image-info.git
version: 1.33_51
