--- 
abstract: Extract meta information from image files (DEPRECATED)
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Image-Info
no_index: 
  directory: 
    - img
    - dev
    - inc
    - t
recommends: 
  Image::Xbm: 1
  Image::Xpm: 1
  XML::Simple: 0
version: 1.26
