--- #YAML:1.0
name:               Image-Info
version:            1.33
abstract:           Extract meta information from image files
author:
    - Slaven Rezic <srezic@cpan.org>
    - Gisle Aas <gisle@ActiveState.com
    - Tels
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006
resources:
    repository:  git://github.com/eserte/image-info.git
no_index:
    directory:
        - t
        - inc
        - dev
        - img
        - xt
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Bundle::Image::Info::PNG:  0
    Bundle::Image::Info::SVG:  0
    Bundle::Image::Info::XBM:  0
    Bundle::Image::Info::XPM:  0
